name: "Multi-Platform Release Package"

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [ "x86_64-linux", "aarch64-linux", "x86_64-darwin", "aarch64-darwin" ]
    steps:
    - name: Check out the repository
      uses: actions/checkout@v4

    - name: Install Nix
      uses: cachix/install-nix-action@v27
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Build for ${{ matrix.platform }}
      run: nix build .#backend_rspass.${{ matrix.platform }}
      env:
        NIXPKGS_ALLOW_UNSUPPORTED_SYSTEM: "1"

    - name: Upload package artifact
      uses: actions/upload-artifact@v3
      with:
        name: release-${{ matrix.platform }}
        path: ./result/bin/backend_rspass

  create-release:
    runs-on: ubuntu-latest
    needs: release
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v3
      with:
        path: ./artifacts

    - name: Create a GitHub Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: |
          ./artifacts/release-x86_64-linux/backend_rspass
          ./artifacts/release-aarch64-linux/backend_rspass
          ./artifacts/release-x86_64-darwin/backend_rspass
          ./artifacts/release-aarch64-darwin/backend_rspass
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ github.ref_name }}
        name: Release ${{ github.ref_name }}
        body: |
          Multi-platform release package for backend_rspass.
